version: '3.8'
services:
  backend:
    build: ./backend/
    ports:
      - 80:8080
    environment:
      - DB_PASSWORD
      - DB_NAME
    depends_on:
      - database
  database:
    image: postgres:14.2-alpine3.15
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
