spring:
  datasource:
    url: jdbc:postgresql://database:5432/${DB_NAME}
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: create-drop
