---
name: Build
on:
  push:
    branches:
      - master
jobs:
  backend-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Run build
        working-directory: backend/
        run: ./mvnw package
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-jar
          path: backend/target/backend-0.0.1-SNAPSHOT.jar
  backend-smoke-test:
    runs-on: ubuntu-20.04
    needs: backend-build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: backend-jar
      - run: java -version
      - name: Start database
        run: docker run -d -e POSTGRES_PASSWORD=admin --network host postgres:14.2-alpine3.15
      - name: Start the application
        run: |
          java -jar backend-0.0.1-SNAPSHOT.jar &
          exit_code=$!
          if [ $exit_code -ne 0]; then
          echo "Failed to start application"
          echo "Exit code: $exit_code"
          exit 1
          fi
          echo "Waiting for the app to start..."
          sleep 2
      - name: Healthcheck
        run: curl --fail localhost:8080/actuator/health
