---
name: Test
on:
  push:
    branches:
      - master
jobs:
  backend-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Start database
        run: docker run -d -e POSTGRES_PASSWORD=admin --network host postgres:14.2-alpine3.15
      - name: Run test
        working-directory: backend/
        run: ./mvnw test
